const Market = require("../models/Market");
const { required, name: validateName, number } = require("../utils/validators");
const User = require("../models/User");
const { buildMapLink } = require("../services/mapService");

function escapeRegex(value) { return String(value).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }

function distanceKm(lat1, lon1, lat2, lon2) { const r=6371; const dLat=(lat2-lat1)*Math.PI/180; const dLon=(lon2-lon1)*Math.PI/180; const a=Math.sin(dLat/2)**2+Math.cos(lat1*Math.PI/180)*Math.cos(lat2*Math.PI/180)*Math.sin(dLon/2)**2; return r*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)); }

async function listMarkets(req,res){
  const filter={isActive:true}; if(req.query.day)filter.operatingDays=req.query.day; if(req.query.search)filter.$or=[{name:{$regex:escapeRegex(String(req.query.search).slice(0,80)),$options:"i"}},{address:{$regex:escapeRegex(String(req.query.search).slice(0,80)),$options:"i"}}];
  let markets=await Market.find(filter).populate("farmers","name farmerProfile");
  if(req.query.lat!==undefined||req.query.lng!==undefined||req.query.radiusKm!==undefined){const lat=Number(req.query.lat),lng=Number(req.query.lng),radius=req.query.radiusKm===undefined?25:Number(req.query.radiusKm);if(!Number.isFinite(lat)||lat<-90||lat>90||!Number.isFinite(lng)||lng<-180||lng>180||!Number.isFinite(radius)||radius<=0||radius>500)return res.status(400).json({success:false,message:"Invalid location or radius"});markets=markets.map(m=>{const x=m.toObject();x.distanceKm=distanceKm(lat,lng,Number(m.latitude),Number(m.longitude));return x;}).filter(m=>Number.isFinite(m.distanceKm)&&m.distanceKm<=radius).sort((a,b)=>a.distanceKm-b.distanceKm);}
  res.json({success:true,markets});
}
async function getMarket(req,res){const market=await Market.findOne({_id:req.params.id,isActive:true}).populate("farmers","name farmerProfile email phone");if(!market)return res.status(404).json({success:false,message:"Market not found"});const data=market.toObject();data.mapLink=data.mapLink||buildMapLink(data);res.json({success:true,market:data});}
async function createMarket(req,res){validateName(req.body.name,"Market name");required(req.body.address,"Address");if(req.body.latitude!==undefined&&req.body.latitude!=="")req.body.latitude=number(req.body.latitude,"Latitude",{min:-90,max:90});if(req.body.longitude!==undefined&&req.body.longitude!=="")req.body.longitude=number(req.body.longitude,"Longitude",{min:-180,max:180});if(req.body.openingTime&&req.body.closingTime&&req.body.openingTime>=req.body.closingTime)return res.status(400).json({success:false,message:"Closing time must be later than opening time"});const market=await Market.create(req.body);res.status(201).json({success:true,market});}
async function updateMarket(req,res){if(req.body.name!==undefined)validateName(req.body.name,"Market name");if(req.body.address!==undefined)required(req.body.address,"Address");if(req.body.latitude!==undefined&&req.body.latitude!=="")req.body.latitude=number(req.body.latitude,"Latitude",{min:-90,max:90});if(req.body.longitude!==undefined&&req.body.longitude!=="")req.body.longitude=number(req.body.longitude,"Longitude",{min:-180,max:180});if(req.body.openingTime&&req.body.closingTime&&req.body.openingTime>=req.body.closingTime)return res.status(400).json({success:false,message:"Closing time must be later than opening time"});const market=await Market.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!market)return res.status(404).json({success:false,message:"Market not found"});res.json({success:true,market});}
async function deleteMarket(req,res){const market=await Market.findByIdAndUpdate(req.params.id,{isActive:false},{new:true});if(!market)return res.status(404).json({success:false,message:"Market not found"});res.json({success:true,message:"Market removed"});}
async function assignFarmer(req,res){const {farmerId}=req.body;const farmer=await User.findOne({_id:farmerId,role:"farmer",isActive:true,"farmerProfile.approvalStatus":"approved"});if(!farmer)return res.status(404).json({success:false,message:"Approved active farmer not found"});const market=await Market.findOne({_id:req.params.id,isActive:true});if(!market)return res.status(404).json({success:false,message:"Market not found"});if(!market.farmers.some(id=>id.toString()===farmerId))market.farmers.push(farmerId);if(!farmer.farmerProfile.markets.some(id=>id.toString()===req.params.id))farmer.farmerProfile.markets.push(req.params.id);await Promise.all([market.save(),farmer.save()]);res.json({success:true,market});}
module.exports={listMarkets,getMarket,createMarket,updateMarket,deleteMarket,assignFarmer};
